name: consolekit
description: $ Console Kit is a tool for creating interactive CLI applications.
version: 0.0.4
repository: https://github.com/medz/consolekit

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
